### ISSUE TITLE
Django 1.8 incompatibility

### ISSUE THREAD

**Issue by cgossy** [matagus/django-generic-links#3]
urls.py:

    from django.conf.urls.defaults import patterns, url

is deprecated since 1.6. See: http://stackoverflow.com/questions/19962736/django-import-error-no-module-named-django-conf-urls-defaults

I wonder why this app is working at all in your projects, because the initial migration has a dependency on Django 1.8 ('contenttypes', '0002_remove_content_type_name').
This kind of error might occur if you don't completely delete  your old django installation before upgrading to a new version (Old/removed files will stay in the django installation directory!)

**Comment by matagus** [comment]
Good catch! And thanks for reporting it. Working on a fix...

**Comment by matagus** [comment]
@cgossy thanks a lot for reporting this issue. I've already fixed it and uploaded a new version to pypi: https://pypi.python.org/pypi/django-generic-links/0.3.1

best
