### ISSUE TITLE
Any interest in me adding a REST API and updating tests to Pytest?

### ISSUE THREAD

**Issue by johnbaldwin** [matagus/django-generic-links#8]
Hi @matagus,

While looking to see how I wanted to implement a "link model", I ran across your package on djangopackages.og (https://djangopackages.org/packages/p/django-generic-links/).

I like that it has a very narrow focus, so I submitted a PR to update dependencies: 

https://github.com/matagus/django-generic-links/pull/7

Now what _this_ issue is about is I need to implement APIs to push/pull links and collections of links for one of my projects.

Would you be interested in a set of PRs that do the following?

1. Upgrade the existing test infra to use Pytest and add test coverage
2. Add REST API using Django REST Framework viewsets and add test coverage for that

**Comment by johnbaldwin** [comment]
Hey @matagus Thanks! Sorry that I missed your message in my git message stream until now. I should have some time over the weekend to add myself to AUTHORS and do a PR for a new version and maybe some other stuff like test coverage.

BTW a couple/three questions
1. Do you have any particular process you want followed for choosing versions and tagging? . I tend to use annotated tags for releases as it has the extra metadata, but if you'd prefer lightweight tags, I can do that
2. What do you want the next version to be that updates the Python and Django versions? Seems to me `v0.8.0` makes sense because of that 
3. Just to confirm: From the GH workflow, looks like the release will happen "auto-magically", so I don't have to worry about pushing to PyPI, right?
4. Are you OK with adding a DRF API to `django-generic-links`?

**Comment by johnbaldwin** [comment]
Hey @matagus! I hope you are well.
I have a hard time believing so much time has gone by. I had some life changing events and now getting myself back into my personal project work that uses Django Generic Links. Thanks for the collaboration invite, but I'm sorry it expired.

**Comment by matagus** [comment]
Do not worry, I already sent it again :)

**Comment by johnbaldwin** [comment]
Thank you!
